/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 서버 상태 확인 */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 일반 DB 검색 */
        get: operations["list_programs_programs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/similar-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 로컬 유사어 DB 검색 */
        get: operations["similar_search_programs_programs_similar_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{program_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 공고 상세 */
        get: operations["get_program_programs__program_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{program_id}/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 관심 여부 변경 */
        patch: operations["update_favorite_programs__program_id__favorite_patch"];
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 카테고리 목록 */
        get: operations["list_categories_categories_get"];
        put?: never;
        /**
         * 카테고리 추가
         * @description 카테고리를 추가한다. 기존 공고에도 반영하려면 /categories/reclassify 를 호출한다.
         */
        post: operations["create_category_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 카테고리 삭제
         * @description 카테고리를 지운다. 공고에 붙어 있던 분류도 함께 사라진다(폴백 ETC 는 지울 수 없음).
         */
        delete: operations["delete_category_categories__code__delete"];
        options?: never;
        head?: never;
        /** 카테고리 수정 */
        patch: operations["update_category_categories__code__patch"];
        trace?: never;
    };
    "/categories/reclassify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 기존 공고 재분류
         * @description 카테고리를 추가·수정한 뒤 이미 저장된 공고를 현재 정의로 다시 분류한다.
         */
        post: operations["reclassify_categories_reclassify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{program_id}/hide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 공고 숨기기(블랙리스트 365일)
         * @description 공고를 DB 에서 지우고 블랙리스트에 올린다.
         *
         *     URL 과 제목 식별키를 함께 저장하므로 같은 사업이 2·3차로 다시 공고돼도 수집하지 않는다.
         */
        post: operations["hide_programs__program_id__hide_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blacklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 숨긴 공고 목록 */
        get: operations["list_blacklist_blacklist_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blacklist/{blacklist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 숨김 해제
         * @description 숨김을 해제한다. 해당 공고는 다음 수집 때 다시 들어온다.
         */
        delete: operations["unhide_blacklist__blacklist_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/crawl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 수집 작업 수동 실행(백그라운드) */
        post: operations["start_crawl_admin_crawl_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crawl/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 수집 진행 상태 조회(공개) */
        get: operations["get_crawl_status_crawl_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AttachmentResponse */
        AttachmentResponse: {
            /** Id */
            id: number;
            /** File Name */
            file_name: string;
            /** Source Url */
            source_url: string;
            /** Mime Type */
            mime_type: string | null;
            /** Size Bytes */
            size_bytes: number | null;
            status: components["schemas"]["AttachmentStatus"];
        };
        /**
         * AttachmentStatus
         * @enum {string}
         */
        AttachmentStatus: "SAVED" | "ANALYZED" | "UNSUPPORTED" | "FAILED";
        /** BlacklistEntryResponse */
        BlacklistEntryResponse: {
            /** Id */
            id: number;
            /** Source Url */
            source_url: string;
            /** Title */
            title: string;
            /** Title Key */
            title_key: string;
            /** Organization */
            organization: string | null;
            /** Reason */
            reason: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** CategoryCreate */
        CategoryCreate: {
            /**
             * Code
             * @description 영문 대문자·숫자·밑줄
             */
            code: string;
            /** Label */
            label: string;
            /**
             * Keywords
             * @description 이 단어가 있으면 해당 카테고리로 분류
             */
            keywords?: string[];
            /**
             * Sort Order
             * @default 100
             */
            sort_order: number;
        };
        /** CategoryResponse */
        CategoryResponse: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Keywords */
            keywords: string[];
            /** Sort Order */
            sort_order: number;
            /** Is Active */
            is_active: boolean;
        };
        /** CategoryUpdate */
        CategoryUpdate: {
            /** Label */
            label?: string | null;
            /** Keywords */
            keywords?: string[] | null;
            /** Sort Order */
            sort_order?: number | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** FavoriteUpdate */
        FavoriteUpdate: {
            /** Is Favorite */
            is_favorite: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HideRequest */
        HideRequest: {
            /** Reason */
            reason?: string | null;
        };
        /**
         * PeriodType
         * @enum {string}
         */
        PeriodType: "FIXED" | "ROLLING" | "UNTIL_BUDGET" | "UNKNOWN";
        /** ProgramPage */
        ProgramPage: {
            /** Items */
            items: components["schemas"]["ProgramResponse"][];
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Total */
            total: number;
            /** Pages */
            pages: number;
        };
        /** ProgramResponse */
        ProgramResponse: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Application Start At */
            application_start_at: string | null;
            /** Application End At */
            application_end_at: string | null;
            application_period_type: components["schemas"]["PeriodType"];
            /** Application Period Text */
            application_period_text: string;
            /** Business Start At */
            business_start_at: string | null;
            /** Business End At */
            business_end_at: string | null;
            /** Business Period Text */
            business_period_text: string | null;
            /** Support Amount Text */
            support_amount_text: string | null;
            /** Support Amount Max */
            support_amount_max: number | null;
            /** Company Burden Text */
            company_burden_text: string | null;
            /** Company Burden Rate */
            company_burden_rate: number | null;
            /** Summary */
            summary: string;
            /** Support Condition */
            support_condition: string;
            /** Organization */
            organization: string;
            /** Relevance */
            relevance: string;
            /** Categories */
            categories: string[];
            /** Regions */
            regions: components["schemas"]["Region"][];
            /** Source Url */
            source_url: string;
            /** Origin Url */
            origin_url: string | null;
            /** Origin Is Direct */
            origin_is_direct: boolean;
            /** Is Favorite */
            is_favorite: boolean;
            /** Attachments */
            attachments: components["schemas"]["AttachmentResponse"][];
        };
        /**
         * Region
         * @description 전국 17개 시·도 + 전국 + 기타.
         * @enum {string}
         */
        Region: "SEOUL" | "BUSAN" | "DAEGU" | "INCHEON" | "GWANGJU" | "DAEJEON" | "ULSAN" | "SEJONG" | "GYEONGGI" | "GANGWON" | "CHUNGBUK" | "CHUNGNAM" | "JEONBUK" | "JEONNAM" | "GYEONGBUK" | "GYEONGNAM" | "JEJU" | "NATIONWIDE" | "ETC";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_programs_programs_get: {
        parameters: {
            query?: {
                /** @description 빈 값이면 전체 조회 */
                q?: string;
                /** @description 카테고리 코드(다중 가능) */
                categories?: string[];
                regions?: components["schemas"]["Region"][];
                period_start?: string | null;
                period_end?: string | null;
                favorite?: boolean | null;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    similar_search_programs_programs_similar_search_get: {
        parameters: {
            query?: {
                /** @description 빈 값이면 전체 조회 */
                q?: string;
                /** @description 카테고리 코드(다중 가능) */
                categories?: string[];
                regions?: components["schemas"]["Region"][];
                period_start?: string | null;
                period_end?: string | null;
                favorite?: boolean | null;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_program_programs__program_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                program_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_favorite_programs__program_id__favorite_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                program_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FavoriteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_categories_get: {
        parameters: {
            query?: {
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_category_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_category_categories__code__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_category_categories__code__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reclassify_categories_reclassify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    hide_programs__program_id__hide_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                program_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["HideRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlacklistEntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_blacklist_blacklist_get: {
        parameters: {
            query?: {
                /** @description 유효기간이 지난 항목도 포함 */
                include_expired?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlacklistEntryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unhide_blacklist__blacklist_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blacklist_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_crawl_admin_crawl_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_crawl_status_crawl_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
